"""Generate the product Skill's allowlisted HTTP reference from current OpenAPI."""

from __future__ import annotations

import argparse
import ast
from pathlib import Path
import re
import sys


ROOT = Path(__file__).resolve().parents[1]
OUTPUT = ROOT / "skills" / "vitalis" / "references" / "api.md"
BASE_OPERATIONS = frozenset({
    "get_data_status", "get_report", "create_analysis_run", "get_job",
    "create_sync_job", "list_workouts", "get_workout", "create_feedback",
    "ingest_bridge_batch",
})
SKILL_SCRIPT = ROOT / "skills" / "vitalis" / "scripts" / "vitalis_api.py"
_PATH_PARAM = re.compile(r"\{[^{}]+\}")


def skill_operations(schema: dict) -> set[str]:
    """Resolve the Skill's literal allowlist against the actual HTTP schema."""
    source = ast.parse(SKILL_SCRIPT.read_text(encoding="utf-8"))
    assignments = {
        target.id: ast.literal_eval(node.value)
        for node in source.body if isinstance(node, ast.Assign)
        for target in node.targets if isinstance(target, ast.Name)
        and target.id in {"READ_OPERATIONS", "WRITE_OPERATIONS"}
    }
    if set(assignments) != {"READ_OPERATIONS", "WRITE_OPERATIONS"}:
        raise ValueError("Skill operation allowlists are missing or not literals")
    requested = [("get", relative) for relative in assignments["READ_OPERATIONS"].values()]
    requested.extend((method.lower(), relative) for method, relative in assignments["WRITE_OPERATIONS"].values())
    found = set()
    for method, relative in requested:
        normalized = _PATH_PARAM.sub("{}", "/api/" + relative)
        matches = [
            operation["operationId"]
            for path, methods in schema["paths"].items()
            if _PATH_PARAM.sub("{}", path) == normalized
            for route_method, operation in methods.items()
            if route_method == method
        ]
        if len(matches) != 1:
            raise ValueError(f"Skill route must match exactly one current API operation: {method} {relative}")
        found.add(matches[0])
    return found


def render_reference(schema: dict) -> str:
    allowed = BASE_OPERATIONS | skill_operations(schema)
    rows = []
    found = set()
    for path, methods in schema["paths"].items():
        for method, operation in methods.items():
            operation_id = operation.get("operationId")
            if operation_id not in allowed:
                continue
            if operation_id in found:
                raise ValueError(f"duplicate product operation: {operation_id}")
            found.add(operation_id)
            required = sorted(
                item["name"] for item in operation.get("parameters", [])
                if item.get("required") and item.get("in") == "header"
            )
            responses = ", ".join(sorted(operation.get("responses", {})))
            rows.append((operation_id, method.upper(), path, ", ".join(required) or "-", responses))
    missing = allowed - found
    if missing:
        raise ValueError(f"missing product operations in OpenAPI: {sorted(missing)}")
    lines = [
        "<!-- Generated by tools/generate_api_reference.py; do not edit manually. -->",
        "# Vitalis HTTP operations",
        "",
        "Set `VITALIS_API_BASE_URL` to the service origin (no path) and store the",
        "`VITALIS_ACCESS_TOKEN` bearer value in private environment configuration.",
        "Authentication and write scopes are enforced by the server. Full field",
        "types and response schemas are available from `GET /openapi.json`.",
        "",
        "| Operation | Method | Path | Required headers | Responses |",
        "| --- | --- | --- | --- | --- |",
    ]
    for operation_id, method, path, required, responses in sorted(rows):
        lines.append(f"| `{operation_id}` | {method} | `{path}` | {required} | {responses} |")
    lines.extend(["", "Read requests do not start a sync or analysis job.", ""])
    return "\n".join(lines)


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="fail when generated API reference differs")
    args = parser.parse_args(argv)
    from vitalis.entrypoints.api.app import app

    try:
        expected = render_reference(app.openapi())
    except ValueError as exc:
        print(f"API reference: {exc}", file=sys.stderr)
        return 1
    if args.check:
        if not OUTPUT.is_file() or OUTPUT.read_text(encoding="utf-8") != expected:
            print("Skill API reference is missing or out of date", file=sys.stderr)
            return 1
        print("Skill API reference matches current OpenAPI")
        return 0
    OUTPUT.write_text(expected, encoding="utf-8")
    print(f"generated {OUTPUT.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
